"""Distance-to-bone skinning (DESIGN §3 skinning, M1).

Every surface vertex was generated by the SDF of one or two nearby bones, so skin
weights fall out of distance-to-bone: for each vertex take the nearest ≤4 bone
*segments*, weight by inverse-square distance, normalize. No separate auto-rigger,
no heat solve (the DESIGN upgrade path if joints pinch).

Fills ``Mesh.joints`` (u16[N,4] bone indices, matching skeleton/glTF joint order)
and ``Mesh.weights`` (f32[N,4]). Deterministic: no RNG, fixed tie-break by bone
index via a stable sort.
"""

from __future__ import annotations

import numpy as np

from .types import Bone, Mesh

_MAX_INFLUENCES = 4  # glTF JOINTS_0/WEIGHTS_0 width
_EPS = 1e-6
_FALLOFF = 2.0  # inverse-distance exponent; higher = more localized weights


def _segment_distances(points: np.ndarray, skel: list[Bone]) -> np.ndarray:
    """Unsigned distance from each point to each bone segment. Returns (N,B)."""
    n = points.shape[0]
    b = len(skel)
    out = np.empty((n, b), dtype=np.float64)
    p = points.astype(np.float64)
    for j, bone in enumerate(skel):
        a = bone.head.astype(np.float64)
        bb = bone.tail.astype(np.float64)
        ba = bb - a
        denom = float(ba @ ba)
        if denom <= 1e-12:
            closest = np.broadcast_to(a, p.shape)
        else:
            h = np.clip(((p - a) @ ba) / denom, 0.0, 1.0)
            closest = a + h[:, None] * ba
        out[:, j] = np.linalg.norm(p - closest, axis=1)
    return out


def skin(mesh: Mesh, skel: list[Bone]) -> Mesh:
    """Return a copy of ``mesh`` with joints/weights filled from bone distances."""
    dist = _segment_distances(mesh.positions, skel)  # (N,B)
    n = dist.shape[0]

    # Nearest MAX_INFLUENCES bones per vertex (argpartition, then stable sort so
    # ties resolve by ascending bone index → deterministic).
    k = min(_MAX_INFLUENCES, dist.shape[1])
    near = np.argpartition(dist, kth=k - 1, axis=1)[:, :k]
    rows = np.arange(n)[:, None]
    near_d = dist[rows, near]
    order = np.argsort(near_d, axis=1, kind="stable")
    near = np.take_along_axis(near, order, axis=1)
    near_d = np.take_along_axis(near_d, order, axis=1)

    raw = 1.0 / (near_d ** _FALLOFF + _EPS)
    weights = raw / raw.sum(axis=1, keepdims=True)

    joints = np.zeros((n, _MAX_INFLUENCES), dtype=np.uint16)
    wfull = np.zeros((n, _MAX_INFLUENCES), dtype=np.float32)
    joints[:, :k] = near.astype(np.uint16)
    wfull[:, :k] = weights.astype(np.float32)

    # Renormalize after float32 cast so rows sum to exactly ~1.
    wfull /= wfull.sum(axis=1, keepdims=True)

    return Mesh(
        positions=mesh.positions,
        normals=mesh.normals,
        indices=mesh.indices,
        uvs=mesh.uvs,
        joints=joints,
        weights=wfull,
    )


def skin_stats(mesh: Mesh) -> dict:
    """Validity stats for the FR5 gate."""
    assert mesh.weights is not None and mesh.joints is not None
    sums = mesh.weights.sum(axis=1)
    nonzero = (mesh.weights > 0).sum(axis=1)
    return {
        "max_weight_error": float(np.abs(sums - 1.0).max()),
        "max_influences": int(nonzero.max()),
        "unweighted_vertices": int((sums <= _EPS).sum()),
        "max_joint_index": int(mesh.joints.max()),
    }
